---
- name: EC2 creation
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    sg_id: sg-0fc9e275bc133b8db
    image_id: ami-0220d79f3f480ecf5
    env: dev
    domain_name: srikanth.digital
    instances:
      - mongodb
      - catalogue

  tasks:
    - name: Create EC2 instances
      amazon.aws.ec2_instance:
        instance_type: t3.micro
        image_id: "{{ image_id }}"
        security_group: "{{ sg_id }}"
        name: "{{ item }}-{{ env }}"
        tags:
          Project: roboshop
          Component: "{{ item }}"
          Environment: "{{ env }}"
          Name: "{{ item }}-{{ env }}"
      loop: "{{ instances }}"
      register: ec2_output

    - name: print the ec2_output
      ansible.builtin.debug:
        msg: "{{ ec2_output }}"   

    - name: creating the route53 record 
      amazon.aws.route53:
        state: present
        zone: "{{ domain_name }}"
        record: "{'{ item.item }'}-{'{ env }'}.{'{ domain_name }'}" # mangodb-dev.srikath.digital 
        type: A
        ttl: 1
        value: "{{ item.instance[0]}.prviate_ip_address }"
        wait: true
        loop: "{{ ec2-ouput.results }}"
    