-name: EC2 creation
host: all
connection: local
become: yes
var:
sg_id: sg-0fc9e275bc133b8db
image_id: ami-0220d79f3f480ecf5
environment: dev
instance:
- mangodb
- catalouge
-tasks: 
   -name: creating the ec2 user
   amazon.aws.ec2_instance:
   instance_type: "t3.micro"
   security_group: "{{ sg_id }}"
   image_id: "{{ image_id }}"
   name: "{{ item }}-{{ environment }}"
   tags:
    - Project: roboshop
    - Component: "{{ item }}" 
    - Environment: "{{ environment}}"
    - name: "{{ item }}-{{ environment }}"
   loop: "{{ instance }}"
   