---
- name: EC2 creation
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    sg_id: sg-0fc9e275bc133b8db
    image_id: ami-0220d79f3f480ecf5
    env: dev
    instances:
      - mongodb
      - catalogue

  tasks:
    - name: Create EC2 instances
      amazon.aws.ec2_instance:
        instance_type: t3.micro
        image_id: "{{ image_id }}"
        security_group: "{{ sg_id }}"
        name: "{{ item }}-{{ env }}"
        tags:
          Project: roboshop
          Component: "{{ item }}"
          Environment: "{{ env }}"
          Name: "{{ item }}-{{ env }}"
      loop: "{{ instances }}"
